modLoader="javafml"
loaderVersion="[54,)"
license="All Rights Reserved"

[[mods]]
modId="simple_hardcore_respawn"
version="2.0.0.r0"
displayName="Simple Hardcore Respawn"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-hardcore-respawn"
logoFile="logo.png"
credits=""
authors="BLES1, Stejser_YT"
description="Respawn in Hardcore!"

[[dependencies.simple_hardcore_respawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.4,1.22)"
    ordering="AFTER"
    side="BOTH"
